### ISSUE TITLE
Enable per-client

### ISSUE THREAD

**Issue by dougwilson** [brianc/node-pg-parse-float#2]
It would be really awesome if it were possible to install the float parsers in only certain clients instead of globally installing it into all clients in the process how it works now.

**Comment by brianc** [comment]
I totally agree.  I thought of that initially but it actually requires some reworking of node-postgres itself since the type parsers are 'global' and each client does not maintain their own copy.  Still would be nice eventually.

**Comment by dougwilson** [comment]
Yea, I did see that things would need to be changed in `pg`. I didn't have any time for now or the near future to work on any patch for you, so I figured I'd just throw this request out here in the meantime in case someone else had the time and/or get a conversation going out of it :panda_face:

**Comment by dougwilson** [comment]
By the way, since v2.0.0 parses floats into JS floats again, this functionality no longer matters to me specifically.
